
const blogData = [
  {
    date: 'July 23, 2022',
    title: 'Learning React',
    preview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit quidem iusto veniam vero? Minus ratione rem provident, voluptatibus nesciunt dicta dolor saepe? Voluptatem aut eius unde quas sequi tenetur molestias.',
    imageUrl: './assets/blog-image-01.webp',
    imageAlt: `computer screen showing React code`,
    bodyHtml: '',
    id: 1,
  },
  {
    date: 'July 13, 2022',
    title: 'Designing Simply',
    preview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id sunt tempore qui eum. Dolores repellendus harum animi, possimus totam laudantium cum tempora deleniti perspiciatis cumque commodi magnam enim. Odit, atque.',
    imageUrl: './assets/blog-image-02.webp',
    imageAlt: `laptop showing quote about design`,
    bodyHtml: '',
    id: 2,
  },
  {
    date: 'July 3, 2022',
    title: 'Learning to Take Breaks',
    preview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id sunt tempore qui eum. Dolores repellendus harum animi, possimus totam laudantium cum tempora deleniti perspiciatis cumque commodi magnam enim. Odit, atque',
    imageUrl: './assets/blog-image-03.webp',
    imageAlt: `woman walking on the beach`,
    bodyHtml: '',
    id: 3,
  },
  {
    date: 'June 23, 2022',
    title: 'Finding Inspiration',
    preview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id sunt tempore qui eum. Dolores repellendus harum animi, possimus totam laudantium cum tempora deleniti perspiciatis cumque commodi magnam enim. Odit, atque',
    imageUrl: './assets/blog-image-04.webp',
    imageAlt: `a person's hand holding a light bulb`,
    bodyHtml: '',
    id: 4,
  },
  {
    date: 'June 13, 2022',
    title: 'Pushing Boundries',
    preview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id sunt tempore qui eum. Dolores repellendus harum animi, possimus totam laudantium cum tempora deleniti perspiciatis cumque commodi magnam enim. Odit, atque',
    imageUrl: './assets/blog-image-05.webp',
    imageAlt: `abstract pattern and colors`,
    bodyHtml: '',
    id: 5,
  },
  {
    date: 'June 3, 2022',
    title: 'Committing to the Process',
    preview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id sunt tempore qui eum. Dolores repellendus harum animi, possimus totam laudantium cum tempora deleniti perspiciatis cumque commodi magnam enim. Odit, atque',
    imageUrl: './assets/blog-image-06.webp',
    imageAlt: `a laptop showing lines of code`,
    bodyHtml: '',
    id: 6,
  },
  // {
  //   date: 'May 23, 2022',
  //   title: 'Test Post',
  //   preview: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Id sunt tempore qui eum. Dolores repellendus harum animi, possimus totam laudantium cum tempora deleniti perspiciatis cumque commodi magnam enim. Odit, atque',
  //   imageUrl: './assets/blog-image-06.webp',
  //   imageAlt: `a laptop showing lines of code`,
  //   bodyHtml: '',
  //   id: 7,
  // },
]

export default blogData